spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/mycrud_db?serverTimezone=Asia/Seoul"
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
jwt:
  secret: "secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeyqowjfasjdklfhaskdjfhaskljdfahfaskljdhfalksjdfhaslkjdfhaslkjdfh"